Numerical Python:- Numpy

In [1]:
import numpy as np 

In [2]:
a=np.array([1,2,3,4]) #1 dementional array
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])#2 DIM 
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Attributes of an array

Shape


In [4]:
a.shape

(4,)

In [5]:
b.shape

(2, 4)

Dimension

In [7]:
a.ndim

1

In [8]:
b.ndim

2

Size

In [9]:
a

array([1, 2, 3, 4])

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
a.size

4

In [12]:
b.size

8

Datatype

In [13]:
c=np.array([1,2,3,4,5],dtype=float)
c

array([1., 2., 3., 4., 5.])

In [14]:
a.dtype

dtype('int64')

In [16]:
print(c.dtype)

float64


item size

In [17]:
a.itemsize

8

In [18]:
b.itemsize

8

reshape()

In [21]:
l=list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
d=np.array(l)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
d.shape

(10,)

In [28]:
d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
d.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [30]:
d.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
d.reshape(-3,5)#-ve value will auto corrected to posssible +ve value like here its two

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Create Numpy arrays

In [33]:
#empty() :- any garbage values array is created:(

np.empty((3,4),dtype=int)

array([[       80223040,               0,            1601,
               62938344],
       [139860802967384, 139860802967384, 139860802967384,
        139860802967384],
       [              0,               1,      4294967296,
                      9]])

In [34]:
#zeros()
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
#ones()
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
#full():- creates all array with the given fill value like 5 over here
np.full((4,5),5,dtype=int)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [40]:
#eye:- diagonal array are created
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
np.eye(3,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [42]:
np.eye(3,5,k=1,dtype=int)#k=1 shift uup diagonal with one line

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [43]:
np.eye(3,5,k=-1,dtype=int)#k=-1 shifts diagonal by -ve one line

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

# Alternate array methods

In [44]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [45]:
t=((2,3),(3,5))
t

((2, 3), (3, 5))

In [47]:
x=np.array(t)
x

array([[2, 3],
       [3, 5]])

In [49]:
l=['sanju',7,9]
np.array(l)

array(['sanju', '7', '9'], dtype='<U21')

# Creating array using Numerical ranges

In [53]:
#arange(start,stop,step,dtype)
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
#linspace()
np.linspace(1,20,100,dtype=int)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,
       14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17,
       17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20])

In [57]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
#indexing and slicing
a=[1,2,3,4,5]
a

In [58]:
a[3]

4

In [61]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[1][2]#a[1,2]

6

In [62]:
a.ndim

2

In [63]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a[0:2,:2]

array([[1, 2],
       [4, 5]])

In [74]:
yes

array([1, 4, 5])

In [67]:
a[0:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a[[0,1,2],[0,1,0]]

array([1, 5, 7])

In [69]:
a[0][0]

1

In [70]:
a[1][1]

5

In [71]:
a[2][0]

7

# Boolean Indexing

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a>3#value >3 True othewise false

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

**Vectorization**

In [77]:
a[a>3] #conditinal filtering array

array([4, 5, 6, 7, 8, 9])

In [78]:
a[a>=3]

array([3, 4, 5, 6, 7, 8, 9])

In [80]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [83]:
a+b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [84]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [85]:
a-b

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [87]:
np.subtract(b,a)

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [88]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [89]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [90]:
a/b

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [92]:
np.divide(a,b)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [95]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

Aggregate Operations

In [96]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
a.max()

9

In [98]:
a.sum()

45

In [99]:
a.min()

1

In [100]:
a.mean()

5.0

In [102]:
np.median(a)

5.0

In [104]:
np.std(a)

2.581988897471611

AXIS

In [105]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
a.max()

9

In [107]:
a.max(axis=0)

array([7, 8, 9])

In [108]:
a.max(axis=1)

array([3, 6, 9])

In [109]:
a.sum(axis=0)

array([12, 15, 18])

In [110]:
a.sum(axis=1)

array([ 6, 15, 24])

In [111]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

Array Comparision

In [112]:
np.array_equal(a,b)

False

### **Broadcasting**

In [113]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [115]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
x

array([[2, 3],
       [3, 5]])

In [117]:
a+x

ValueError: ignored

In [118]:
a1=np.array([1,2,3])

In [124]:
a1

array([1, 2, 3])

In [120]:
a+a1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [121]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
y=np.arange(1,4)
y

array([1, 2, 3])

In [131]:
z=y.reshape(3,1)
z

array([[1],
       [2],
       [3]])

In [133]:
y+z

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])