In [5]:
import numpy as np

In [6]:
#from google.colab import files
#uploaded =files.uploaded

# Step 1

In [7]:
data_file='/content/drive/MyDrive/Python /Numpy Library/census.csv'
data=np.genfromtxt(data_file,delimiter=',',skip_header=1)

In [8]:
print('\nData: \n\n',data)
print("\nType of data: \n\n",type(data))


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>


In [9]:
data.shape

(1000, 8)

In [10]:
new_record=[[50,9,4,1,0,0,40,0]]

In [11]:
#new_record=np.array([[50,9,4,1,0,0,40,0]])

In [12]:
census=np.concatenate((data,new_record),axis=0)

In [13]:
data.shape

(1000, 8)

In [14]:
census.shape

(1001, 8)

In [15]:
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 2

In [16]:
age=census[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [17]:
max_age=age.max()
max_age

90.0

In [18]:
min_age=age.min()
min_age

17.0

In [19]:
age_mean=age.mean()
age_mean
round(age_mean,2)

38.06

In [20]:
age_std=age.std()
age_std

13.341478176165857

The country is young!!

# Step 3

In [21]:
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [22]:
a=census[:,2]
race_0=a[a==0]
race_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
race_1=a[a==1]
race_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
race_2=a[a==2]
race_2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [25]:
race_3=a[a==3]
race_3

array([3., 3., 3., 3., 3., 3.])

In [26]:
race_4=a[a==4]
race_4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [27]:
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)

In [28]:
print('race_0= ',len_0)
print('race_1= ',len_1)
print('race_2= ',len_2)
print('race_3= ',len_3)
print('race_4= ',len_4)

race_0=  10
race_1=  27
race_2=  110
race_3=  6
race_4=  848


In [29]:
minority_race=3
print('minority_race is ',minority_race,' with ',len_3,' number of citizens')

minority_race is  3  with  6  number of citizens


# Step 4

In [30]:
age=census[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [37]:
senior_citizens=census[age>60]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [38]:
working_hours=census[:,6]
working_hours

array([40., 13., 40., ..., 40., 50., 40.])

In [39]:
w=working_hours[working_hours<25]
w

array([13., 16., 20., 15., 20.,  2., 22., 20., 24., 24.,  2., 20., 16.,
       20., 12.,  1., 24., 12., 20., 10., 20., 20., 20., 20., 12., 24.,
       24., 15., 16., 15., 24., 10., 15., 20.,  8., 24., 15., 15., 10.,
       10.,  6., 16., 24., 19., 18., 24.,  5., 20., 16., 24.,  6., 20.,
       20., 20., 20., 20.,  8., 20., 24.,  9.,  8., 20., 12., 24., 21.,
       20., 20., 20., 24., 14., 15., 20., 15., 20., 10., 16.,  5.,  4.,
       20., 20., 20., 15., 20., 24., 15., 20., 20., 20., 18., 24., 16.,
       20., 20., 20., 20., 24., 15., 24.,  6., 20., 18., 20., 15.,  7.,
       15., 20., 15., 10., 20.,  5., 10., 20., 20., 20., 20., 20.])

In [41]:
working_hours_sum=sum(w)
working_hours_sum

1953.0

In [42]:
senior_citizens_len=len(senior_citizens)
senior_citizens_len

61

In [36]:
avg_working_hours=working_hours_sum/senior_citizens_len
avg_working_hours

32.01639344262295